name: Asset size

on: [pull_request]

jobs:
  compare:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write

    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - name: Install pnpm
        uses: pnpm/action-setup@v6
      - uses: actions/setup-node@v6
        with:
          node-version-file: '.node-version'
          cache: 'pnpm'
      - uses: chrysanthos/simple-asset-size-reporter@1.0.2
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          files: '["dist/*.js"]'
          with-same: "false"
          build-assets: "pnpm run prepare-and-install"
